require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - bin/*

Style/Documentation:
  # Using yard to check it
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Lint/AmbiguousBlockAssociation:
  # REVIEW: why is that dangerous?
  Enabled: false

RSpec/FilePath:
  CustomTransform:
    XVerifier: xverifier
