inherit_gem:
  rubocop-config-umbrellio: lib/rubocop.yml

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - bin/*

Style/Documentation:
  # Using yard to check it
  Enabled: false

RSpec/EmptyLineAfterHook:
  Enabled: false
